# servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-sm
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      prometheus-monitored: "true"
  namespaceSelector:
    matchNames: ["default"]
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
